name: quant
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.7
  - mkl
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  - pandas_ta
  - pyarrow >=1.0
  - pandas >=1.1
  - pandas_market_calendars
  - ipython
  - ipdb
  - jupyterlab
  - dask
  - distributed
  - cachey
  - tenacity
  - prefect[viz, gcp, aws]
  - boto3
  - google-api-python-client
  - requests
  - fsspec
  - s3fs
  - tqdm
  - matplotlib
  - graphviz
  - bokeh
  - qgrid
  - pip
  - pip:
    - pandas-ta
    - pandas-bokeh
    - finplot
    - ray
