name: quant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - mkl
  # - nomkl
  # - openblas
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  # - category_encoders
  # - fastcluster
  # - pyclustering
  # - pingouin
  - pyarrow>=2.0
  - pandas>=1.1
  - pandas_market_calendars
  - ipython
  - ipdb
  - filprofiler
  - jupyterlab
  - dask
  - distributed
  # - modin
  # - swifter
  # - psutil
  - cachey
  - tenacity
  - prefect[viz, gcp, aws]
  - boto3
  - google-api-python-client
  - requests
  - trio
  - fsspec
  - s3fs
  - tqdm
  - matplotlib
  - bokeh
  - qgrid
  # - cvxpy
  # - numba
  # - pot
  # - networkx
  # - graphviz
  # - dash
  # - dash-bootstrap-components
  - pip
  - pip:
    - trio-websockets
    - pandas-ta
    - finta
    # - fracdiff
    - pandas-bokeh
    - finplot
    - ray[tune]
    - tune-sklearn
    # - skranger
    # - ppscore
    # - persist-queue[extra]
    # - dcor

# pip install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o
# brew tap adoptopenjdk/openjdk
# brew cask install adoptopenjdk14
